export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";

export const LOG_OUT = "LOG_OUT";

export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const FIND_USER_PENDING = "FIND_USER_PENDING";
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_ERROR = "FIND_USER_ERROR";

export const FETCH_FRIEND_PENDING = "FETCH_FRIEND_PENDING";
export const FETCH_FRIEND_SUCCESS = "FETCH_FRIEND_SUCCESS";
export const FETCH_FRIEND_ERROR = "FETCH_FRIEND_ERROR";
export const FETCH_FRIEND_SUCCESS_MESS = "FETCH_FRIEND_ERROR";
